services:
  beatnik:
    image: ghcr.io/byrdsandbytes/beatnik-controller:latest
    container_name: beatnik-controller
    ports:
      - "80:80"
      - "8443:443"
  icecast:
    image: ghcr.io/libretime/icecast:2.4.4
    container_name: icecast
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD=beatnik
      - ICECAST_ADMIN_PASSWORD=beatnik
      - ICECAST_PASSWORD=beatnik
      - ICECAST_RELAY_PASSWORD=beatnik

  snapcast-to-icecast:
    image: alpine:latest
    container_name: snapcast-to-icecast
    restart: always
    depends_on:
      - beatnik
      - icecast
    entrypoint: /bin/sh -c
    command: >
      apk add --no-cache ffmpeg snapcast-client &&
      mkfifo /tmp/stream_fifo || true;
      snapclient -h host.docker.internal -s 1 --player file:name=/tmp/stream_fifo &
      sleep 5;
      ffmpeg -re -f s16le -ar 48000 -ac 2 -i /tmp/stream_fifo -acodec libmp3lame -b:a 192k -content_type audio/mpeg icecast://source:beatnik@icecast:8000/stream