services:
  beatnik:
    image: ghcr.io/byrdsandbytes/beatnik-controller:latest
    container_name: beatnik-controller
    ports:
      - "80:80"
      - "8443:443"
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"

  icecast:
    image: ghcr.io/libretime/icecast:2.4.4
    container_name: icecast
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD=beatnik
      - ICECAST_ADMIN_PASSWORD=beatnik
      - ICECAST_PASSWORD=beatnik
      - ICECAST_RELAY_PASSWORD=beatnik

  snapcast-to-icecast:
    image: ghcr.io/linuxserver/ffmpeg
    container_name: snapcast-to-icecast
    restart: always
    depends_on:
      - beatnik
      - icecast
    entrypoint: /bin/sh -c
    command: >
      "
      # Install snapclient
      apk add --no-cache snapcast-client

      # Create pipe
      mkfifo /tmp/stream_fifo || true

      # Start snapclient (-h points to beatnik container as snapserver)
      snapclient -h beatnik-controller -s 1 --player file:name=/tmp/stream_fifo &

      sleep 5

      # Encode and push to Icecast
      ffmpeg -re -f s16le -ar 48000 -ac 2 -i /tmp/stream_fifo \
             -acodec libmp3lame -b:a 192k -content_type audio/mpeg \
             icecast://source:beatnik@icecast:8000/stream
      "
